Time range

diff --git a/devopsfetch b/devopsfetch
--- a/devopsfetch
+++ b/devopsfetch
@@ -34,10 +34,19 @@ users(){
     last | awk '!seen[$1]++ {print $1, $3, $4, $5, $6, $7}' | column -t
 }
 
-# # Time range
-# time_range(){
-
-# }
+# Time range
+time_range(){
+    if [ -z "$1" ]; then
+        echo "Error: No date provided. Usage: devopsfetch -t YYYY-MM-DD [YYYY-MM-DD]"
+        return 1
+    fi
+    
+    start_date=$1
+    end_date=${2:-$start_date}
+    
+    echo "Activities from $start_date to $end_date:"
+    journalctl --since "$start_date" --until "$end_date 23:59:59" | tail -n 50
+}
 
 # Help
 help(){
@@ -59,11 +68,11 @@ help(){
 
 # Process options when the devopsfetch is called
 case "$1" in
-        -p | --ports) 
+        -p|--ports) 
             ports "$2"
             ;;
 
-        -d | --docker) 
+        -d|--docker) 
             docker_info "$2"
             ;;
 
@@ -72,21 +81,21 @@ case "$1" in
         #     ;;
 
         -u|--users)
-        users "$2"
+            users "$2"
             ;;
 
-        # t | --time) 
-
-        #     ;;
+        -t|--time) 
+            time_range "$2" "$3"
+            ;;
         
         -h|--help)
-        help
+            help
         ;;
 
         *)
-        echo "Invalid option. Use -h or --help for usage information."
-        help
-        exit 1
-        ;;
+            echo "Invalid option. Use -h or --help for usage information."
+            help
+            exit 1
+            ;;
 
 esac
